[package]
name = "circuit"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]
bench = false

[dependencies]
aes = "0.8.4"
hex = "0.4.3"
num = {version = "0.4.3", features = []}
#rand = "0.8"
getrandom = { version = "0.3.1", features = ["wasm_js"] }
sha3 = "0.10.8"
